# SITE CONFIGURATION
baseurl: ""
url: "https://cweinschenk.github.io"
title: cweinschenk # site's title
description: "Fire - Data - Travel" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: cweinschenk # blog's title
  avatar: assets/icon.png
  favicon: assets/icon.png
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: Fire - Data - Travel
  header_feature_image: assets/img/travel/elephant_walk.jpg
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a>

  # Icons
  rss:  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "cweinschenk"
  google_plus:
  instagram: "cweinschenk"
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "cweinschenk"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options

  # Scripts / Features 
  google_analytics: UA-23057944-1
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search"
      enabled: true
    tags:
      icon: "tags"
      enabled:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
